name: CI

on: [push]

jobs:
  build-clj:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    name: Clojure

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup clojure-lsp
        uses: clojure-lsp/setup-clojure-lsp@v1
        with:
          clojure-lsp-version: 2025.03.07-17.42.36

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: 1.11.4.1474

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: ${{ runner.os }}-clj-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: clojure-lsp
        run: clojure-lsp diagnostics

      - name: splint
        run: clojure -M:dev:test:splint

      - name: tests
        run: |
          clojure -M:dev:test:runner

  build-cljs:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: ClojureScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.m2/repository
          key: ${{ runner.os }}-cljs-${{ hashFiles('deps.edn') }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-cljs-

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          cli: 1.11.4.1474

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: run node tests
        run: npx shadow-cljs compile node-test && node target/shadow-node-test/node-tests.js
